const Capabilities = {
    DIAGNOSTICS: 'DIAGNOSTICS',
    TIME_SOURCE: 'TIME_SOURCE',
    DIAGNOSTIC_EVENT_EMITTER: 'DIAGNOSTIC_EVENT_EMITTER',
    DIAGNOSTIC_EVENT_FORMATTER: 'DIAGNOSTIC_EVENT_FORMATTER',
    DIAGNOSTICS_ORIGIN: 'DIAGNOSTICS_ORIGIN',
};

export default Capabilities;
