const Capabilities = {
    DIAGNOSTICS: 'DIAGNOSTICS',
    DIAGNOSTIC_EVENT_EMITTER: 'DIAGNOSTIC_EVENT_EMITTER',
    DIAGNOSTIC_EVENT_FORMATTER: 'DIAGNOSTIC_EVENT_FORMATTER',
};

export default Capabilities;
